Add login routine to all tests
Factotum-sdp/Factotum pull request #171
Opened 2023-05-02 18:24 UTC by yanvow

2023-05-02 20:01 UTC, jules552 approved these changes
Not much to review here, a nice addition to finally stop using the work around!

2023-05-02 23:17 UTC, schuetzcarl approved these changes
I approve, but check my single comment.
Thank you for updating the whole tests according to the login.

2023-05-02 23:17 UTC, schuetzcarl commented on app/src/androidTest/java/com/github/factotum_sdp/factotum/ui/roadbook/RoadBookFragmentTest.kt
>          onView(withId(R.id.drawer_layout))
For the RoadBook, the following three lines could be removed, as it is the first Fragment after the login entry.

Also remark that for all other Fragment, a wrong user-entry will still being bypassed by an open action on the DrawerMenu, but I don't think it is a problem for our before routine.

2023-05-03 10:03 UTC, schuetzcarl commented
@yanvow, It seems that the new login routine fails on the CI our witness is the RoadBookFragmentTest, having removed the Drawer bypass action seems not working on the CI, even if it succeed locally..

It's probable that for the others FragmentTest classes, it also fails and the Drawer is still used to enter the app.

Maybe for the CI we should let uniformly the Drawer by pass action, and set in all @before the current loggedInUser attribute of the application's UserViewModel. For that, we can add a getter for the UserViewModel in the MainActivity.

Thus, not all the test will depends on the flaky Firebase behavior seen on the CI.

2023-05-03 10:06 UTC, schuetzcarl requested changes
Comment needed for the the approval status update.

2023-05-03 14:40 UTC, schuetzcarl approved these changes
As time flies and it is needed for #168, I changed it myself for all test classes and it seems to be good.

2023-05-03 14:45 UTC, merged