Feature/see history on mailbox click
Factotum-sdp/Factotum pull request #229
Opened 2023-05-17 21:36 UTC by DanielTavaresA

2023-05-24 13:21 UTC, TimVW7 requested changes
Really nice code and understandable code. Just a few adjustments and it is good to go. Also the UI for displaying the history could use a bit of work but its good enough for now.

2023-05-24 13:21 UTC, TimVW7 commented on app/src/main/java/com/github/factotum_sdp/factotum/ui/display/DisplayFragment.kt
> +        val proofPicture = arguments?.getString("ProofPicture")
Maybe change the "ProofPicture" value to a constant, so it may be easier to switch in the future.

2023-05-24 13:21 UTC, TimVW7 commented on app/src/main/java/com/github/factotum_sdp/factotum/ui/maps/BossMapFragment.kt
>  class BossMapFragment : Fragment(), OnMapReadyCallback {
Would be good to add a description since it's a public class.

2023-05-24 13:21 UTC, TimVW7 commented on app/src/main/java/com/github/factotum_sdp/factotum/ui/maps/BossMapFragment.kt
> +                    Toast.makeText(requireContext(), "No history available", Toast.LENGTH_SHORT)
Could be good to add a test case when a contact doesn't have any history.

2023-05-24 13:21 UTC, TimVW7 commented on app/src/main/java/com/github/factotum_sdp/factotum/ui/maps/BossMapViewModel.kt
> +                    user.children.forEach { date ->
Would be good to test this function.

2023-05-25 12:14 UTC, TimVW7 approved these changes
Thanks for applying some of the changes, when you have some time, maybe look at the issues from code climate, they might be worth reviewing. Otherwise good to go !

2023-05-25 13:16 UTC, DanielTavaresA commented
> Thanks for applying some of the changes, when you have some time, maybe look at the issues from code climate, they might be worth reviewing. Otherwise good to go !

Although I agree with you that code climate issues should be addressed, now the necessity of the feature is worth more of the code quality. Time issues makes it hard for me to address this right now.

2023-05-25 16:08 UTC, merged